FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

COPY src/ ./src/

RUN dotnet restore src/OrderProcessing.DbMigrator/OrderProcessing.DbMigrator.csproj

RUN dotnet publish src/OrderProcessing.DbMigrator/OrderProcessing.DbMigrator.csproj \
    -c Release -o /publish

FROM mcr.microsoft.com/dotnet/runtime:8.0
WORKDIR /app
COPY --from=build /publish .

ENTRYPOINT ["dotnet", "OrderProcessing.DbMigrator.dll"]